version: "2.2"
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - /nfs-share/streamlit/st-mysql/:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: centos@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: sysadmin
      MYSQL_PASSWORD: centos@123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: sysadmin
      PMA_PASSWORD: centos@123
    ports:
      - "8011:80"  
