version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - /nfs-share/streamlit/st-mysql/:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: streamlit
      MYSQL_DATABASE: streamlit
      MYSQL_USER: root
      MYSQL_PASSWORD: streamlit
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: streamlit
    ports:
      - "8013:80"  
