version: "3"
services:
  streamlit-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: streamlit
      MYSQL_DATABASE: streamlit
      MYSQL_USER: streamlit
      MYSQL_PASSWORD: streamlit
    volumes:
      - $PWD/mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - streamlit-db
    restart: always
    environment:
      PMA_HOST: streamlit-db
      PMA_USER: streamlit
      PMA_PASSWORD: streamlit
    ports:
      - "8012:80"
